# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 600)
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(180, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 283, 511, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelRef = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelRef.setObjectName("labelRef")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelRef)
        self.comboBoxRef = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxRef.setMaximumSize(QtCore.QSize(16777215, 400))
        self.comboBoxRef.setObjectName("comboBoxRef")
        self.comboBoxRef.addItem("")
        self.comboBoxRef.addItem("")
        self.comboBoxRef.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxRef)
        self.labelUSD = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelUSD.setObjectName("labelUSD")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelUSD)
        self.lineEditUSD = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditUSD.setObjectName("lineEditUSD")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditUSD)
        self.labelPHP = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPHP.setObjectName("labelPHP")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelPHP)
        self.lineEditPHP = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditPHP.setObjectName("lineEditPHP")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditPHP)
        self.labelIDR = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelIDR.setObjectName("labelIDR")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelIDR)
        self.lineEditIDR = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditIDR.setObjectName("lineEditIDR")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditIDR)
        self.btnCondifgure = QtWidgets.QPushButton(Dialog)
        self.btnCondifgure.setGeometry(QtCore.QRect(70, 513, 221, 51))
        self.btnCondifgure.setObjectName("btnCondifgure")
        self.btnLoadRates = QtWidgets.QPushButton(Dialog)
        self.btnLoadRates.setGeometry(QtCore.QRect(340, 513, 221, 51))
        self.btnLoadRates.setObjectName("btnLoadRates")
        self.labelImage = QtWidgets.QLabel(Dialog)
        self.labelImage.setGeometry(QtCore.QRect(50, 70, 511, 200))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("logo.jpg"))
        self.labelImage.setScaledContents(True)
        self.labelImage.setObjectName("labelImage")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Currency Converter"))
        self.labelTitle.setText(_translate("Dialog", "Currency Converter"))
        self.labelRef.setText(_translate("Dialog", "Reference"))
        self.comboBoxRef.setItemText(0, _translate("Dialog", "USD"))
        self.comboBoxRef.setItemText(1, _translate("Dialog", "PHP"))
        self.comboBoxRef.setItemText(2, _translate("Dialog", "IDR"))
        self.labelUSD.setText(_translate("Dialog", "USD"))
        self.labelPHP.setText(_translate("Dialog", "PHP"))
        self.labelIDR.setText(_translate("Dialog", "IDR"))
        self.btnCondifgure.setText(_translate("Dialog", "Configure"))
        self.btnLoadRates.setText(_translate("Dialog", "Load Rates"))
